PROCESS BEFORE OUTPUT.
  MODULE status_0100.
  CALL SUBSCREEN SUB_SEL INCLUDING sy-repid '0101'.

PROCESS AFTER INPUT.
  MODULE exit_0100 AT EXIT-COMMAND.
  CALL SUBSCREEN SUB_SEL.
  MODULE user_command_0100.
